name: DebugBuild
on:
  push:
    branches:
      - master
env:
  SOLUTION_FILE_PATH: Project/SabTusEngine.sln
  CONFIGURATION: Debug

jobs:
  build:
    # マトリックスで定義したOS（windows-2022 または windows-2026）が動的に入ります
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false # 片方の環境が落ちても、もう片方のビルドを中断せず最後まで実行する
      matrix:
        os: [windows-latest, windows-2022]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64
          
      - name: Restore NuGet Packages
        run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    
      - name: Build
        run: |
          msbuild ${{env.SOLUTION_FILE_PATH}} /p:Platform=x64,Configuration=${{env.CONFIGURATION}}
